### ISSUE TITLE
gimptool-2.0 failed and manually make'ing and cp'ing didnt work either

### ISSUE THREAD

**Issue by ghost** [bbbbbr/gimp-rom-bin#2]
i tried with gimptool-2.0 firstly but couldnt find file etc, then renamed to fit ./src/file-rom-bin.c and that didnt work either. dumps below.

lastly from /home/e/stream/nesdev/git/gimp-rom-bin i ran make, compile successful so i took a guess and copied contents of ./obj/ into this system's gimp plug-in dir at /home/e/.config/GIMP/2.10/plug-ins/

when i started gimp i didnt receive any extra file opening superpowers and at this point became stuck as what to do.

advice please?

> [e@e-pc gimp-rom-bin]$ gimptool-2.0 --install file-rom-binfile.c
> gcc  -I/usr/include/gimp-2.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/uuid -I/usr/include/gegl-0.4 -I/usr/include/json-glib-1.0 -I/usr/include/gio-unix-2.0 -I/usr/include/babl-0.1 -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/atk-1.0 -pthread  -o '/home/e/.config/GIMP/2.10/plug-ins/file-rom-binfile' 'file-rom-binfile.c'  -lgimpui-2.0 -lgimpwidgets-2.0 -lgimpmodule-2.0 -lgimp-2.0 -lgimpmath-2.0 -lgimpconfig-2.0 -lgimpcolor-2.0 -lgimpbase-2.0 -lgegl-0.4 -lgegl-npd-0.4 -lm -Wl,--export-dynamic -pthread -lgmodule-2.0 -ljson-glib-1.0 -lbabl-0.1 -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lharfbuzz -lfontconfig -lfreetype  
> gcc: error: file-rom-binfile.c: No such file or directory
> [e@e-pc gimp-rom-bin]$ pwd
> /home/e/stream/nesdev/git/gimp-rom-bin
> [e@e-pc gimp-rom-bin]$ 
> 

> 
> [e@e-pc gimp-rom-bin]$ cd src/
> [e@e-pc src]$ gimptool-2.0 --install file-rom-binfile.c
> gcc  -I/usr/include/gimp-2.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/uuid -I/usr/include/gegl-0.4 -I/usr/include/json-glib-1.0 -I/usr/include/gio-unix-2.0 -I/usr/include/babl-0.1 -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/atk-1.0 -pthread  -o '/home/e/.config/GIMP/2.10/plug-ins/file-rom-binfile' 'file-rom-binfile.c'  -lgimpui-2.0 -lgimpwidgets-2.0 -lgimpmodule-2.0 -lgimp-2.0 -lgimpmath-2.0 -lgimpconfig-2.0 -lgimpcolor-2.0 -lgimpbase-2.0 -lgegl-0.4 -lgegl-npd-0.4 -lm -Wl,--export-dynamic -pthread -lgmodule-2.0 -ljson-glib-1.0 -lbabl-0.1 -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lharfbuzz -lfontconfig -lfreetype  
> gcc: error: file-rom-binfile.c: No such file or directory
> [e@e-pc src]$ 
> 

i changed filename to point to file-rom-bin.c but that failed also

> 
> [e@e-pc src]$ gimptool-2.0 --install file-rom-bin.c
> gcc  -I/usr/include/gimp-2.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/uuid -I/usr/include/gegl-0.4 -I/usr/include/json-glib-1.0 -I/usr/include/gio-unix-2.0 -I/usr/include/babl-0.1 -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/atk-1.0 -pthread  -o '/home/e/.config/GIMP/2.10/plug-ins/file-rom-bin' 'file-rom-bin.c'  -lgimpui-2.0 -lgimpwidgets-2.0 -lgimpmodule-2.0 -lgimp-2.0 -lgimpmath-2.0 -lgimpconfig-2.0 -lgimpcolor-2.0 -lgimpbase-2.0 -lgegl-0.4 -lgegl-npd-0.4 -lm -Wl,--export-dynamic -pthread -lgmodule-2.0 -ljson-glib-1.0 -lbabl-0.1 -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lharfbuzz -lfontconfig -lfreetype  
> /usr/bin/ld: /tmp/ccn1Zb6y.o: in function `run':
> file-rom-bin.c:(.text+0x3fe): undefined reference to `export_dialog'
> /usr/bin/ld: file-rom-bin.c:(.text+0x437): undefined reference to `read_rom_bin'
> /usr/bin/ld: file-rom-bin.c:(.text+0x595): undefined reference to `export_dialog'
> /usr/bin/ld: file-rom-bin.c:(.text+0x5c2): undefined reference to `write_rom_bin'
> collect2: error: ld returned 1 exit status
> [e@e-pc src]$ 
>

**Comment by bbbbbr** [comment]
I just did a test on a clean Debian 10 VM and the following worked. I've updated the Readme to include these more detailed steps. Hopefully they work for you.

(Also, I added a link to the compiled binaries available in this repo)

```
If GIMP & build tools not yet installed:
(example for debian/ubuntu/mint)
 * sudo apt install gimp
 * sudo apt install build-essential
 * sudo apt install libgimp2.0-dev
 
Then: 
* cd gimp-rom-bin
* make

Then copy the resulting "file-rom-bin" to your GIMP plugin folder, depends on version

Plug-in folder locations:
 Linux: ~/.gimp-2.8/plug-ins  , or ~/.config/GIMP/2.10/plug-ins

```

**Comment by ghost** [comment]
That worked perfectly on manjaro.
Dude! Very happy thank you!
