### ISSUE TITLE
pkm support

### ISSUE THREAD

**Issue by DIESLTEK710** [bbbbbr/gimp-rom-bin#4]
Would it be possible to add pkm file support? as a majority of sprites now user pkm / pkm10

**Comment by bbbbbr** [comment]
This plugin is only meant for loading executable rom files with embedded graphics, so normal image file formats are outside of the scope. Perhaps there should be a separate GIMP plugin to support PKM.

What kind of tools and systems do PKM and PKM10 files get used with?

Are you referring to the grafx2 image format or a different one? If a different one, is there are formal specification available?
