### ISSUE TITLE
So about your plug in

### ISSUE THREAD

**Issue by Mysterypome** [bbbbbr/gimp-rom-bin#5]
I've been trying to get into the gimp rom bin file but every time I click on the program, I get I .dll error surrounding libgimp(something)2.0-0 do you have any of the files I could use or could I have another version of the program?

**Comment by bbbbbr** [comment]
More information would be helpful to understand this:
- What version of GIMP?
- What operating system? (windows?)
- Where is the file installed to?

You might also try an older version of GIMP
Around:
- Linux GIMP ~2.8
- Windows GIMP ~2.10.12

**Comment by Mysterypome** [comment]
the version of gimp I have is just 2.10, I tried to find gimp 2.0 with no
luck, could you send me a link to the download.

**Comment by bbbbbr** [comment]
I checked the current plugin build on Windows with GIMP `2.10.04` which can be found here:
https://download.gimp.org/gimp/v2.10/windows/

It probably works with some other versions in there too.

I downloaded the latest for Windows (`2.10.38`) and that works too.
